# Generated by Django 5.1 on 2024-09-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PS', 'Phones'), ('LT', 'Laptops'), ('CS', 'Cameras'), ('DC', 'Data cables'), ('AP', 'Airpodes'), ('SW', 'Smart Watch')], max_length=2),
        ),
    ]
